/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Multibodega;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Brayan Cifuentes
 */
public class Venta_Detalle extends javax.swing.JInternalFrame {

    /**
     * Creates new form Venta_Detalle
     */
    public Venta_Detalle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txt_ID_VentaE = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_estatus = new javax.swing.JLabel();
        txt_ID_Inventario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_ID_Productos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_Orden_Venta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_Cantidad_Venta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_Costo_Venta = new javax.swing.JTextField();
        txt_buscar = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txt_Precio_Venta = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Venta Detalle:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 22, -1, -1));

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 99, -1, -1));

        jLabel2.setText("ID Venta Encabezado:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 99, -1, -1));
        getContentPane().add(txt_ID_VentaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 101, -1));

        jLabel11.setText("Ingrese el Orden de Venta:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 147, -1, -1));

        jLabel3.setText("ID Inventario:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        lbl_estatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(lbl_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 235, 180, 27));
        getContentPane().add(txt_ID_Inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 101, -1));

        jLabel6.setText("ID Producto:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));
        getContentPane().add(txt_ID_Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 101, -1));

        jLabel7.setText("Orden Venta:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));
        getContentPane().add(txt_Orden_Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 101, -1));

        jLabel9.setText("Cantidad Venta:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        getContentPane().add(txt_Cantidad_Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 101, -1));

        jLabel10.setText("Costo Venta:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        getContentPane().add(txt_Costo_Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 101, -1));
        getContentPane().add(txt_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 143, 106, -1));

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 185, -1, -1));

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 99, -1, -1));

        jLabel12.setText("Precio Venta:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));
        getContentPane().add(txt_Precio_Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 101, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Codigo que permite modificar registros en la base de datos
        try {
            String ID = txt_buscar.getText().trim();

            Connection cn = DriverManager.getConnection(Multibodega.Base_de_Datos, Multibodega.Usuario, Multibodega.Clave);
            PreparedStatement pst = cn.prepareStatement("update Venta_Detalle set Orden_Venta = ?, Precio_Venta=?, Cantidad=?, Costo_Venta=?, Id_Inventario=?, Id_Productos=?, Id_Venta_Encabezado=? where Orden_Venta = " + ID);

            pst.setString(1, txt_Orden_Venta.getText().trim());
            pst.setString(2, txt_Precio_Venta.getText().trim());
            pst.setString(3, txt_Cantidad_Venta.getText().trim());
            pst.setString(4, txt_Costo_Venta.getText().trim());
            pst.setString(5, txt_ID_Inventario.getText().trim());
            pst.setString(6, txt_ID_Productos.getText().trim());
            pst.setString(7, txt_ID_VentaE.getText().trim());

            pst.executeUpdate();

            txt_buscar.setText("");
            lbl_estatus.setText("Modificación exitosa.");

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Codigo que permite borrar registros en la base de datos
        try {
            Connection cn = DriverManager.getConnection(Multibodega.Base_de_Datos, Multibodega.Usuario, Multibodega.Clave);
            PreparedStatement pst = cn.prepareStatement("delete from Venta_Detalle where Orden_Venta = ?");

            pst.setString(1, txt_buscar.getText().trim());
            pst.executeUpdate();

            txt_Orden_Venta.setText("");
            txt_Precio_Venta.setText("");
            txt_Cantidad_Venta.setText("");
            txt_Costo_Venta.setText("");
            txt_ID_Inventario.setText("");
            txt_ID_Productos.setText("");
            txt_ID_VentaE.setText("");

            lbl_estatus.setText("Registro eliminado.");

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        //Codigo que permite consultar registros en la base de datos
        try {
            Connection cn = DriverManager.getConnection(Multibodega.Base_de_Datos, Multibodega.Usuario, Multibodega.Clave);
            PreparedStatement pst = cn.prepareStatement("select * from Venta_Detalle where Orden_Venta = ?");
            pst.setString(1, txt_buscar.getText().trim());

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_Orden_Venta.setText(rs.getString("Orden_Venta"));
                txt_Precio_Venta.setText(rs.getString("Precio_Venta"));
                txt_Cantidad_Venta.setText(rs.getString("Cantidad"));
                txt_Costo_Venta.setText(rs.getString("Costo_Venta"));
                txt_ID_Inventario.setText(rs.getString("Id_Inventario"));
                txt_ID_Productos.setText(rs.getString("Id_Productos"));
                txt_ID_VentaE.setText(rs.getString("Id_Venta_Encabezado"));

            } else {
                JOptionPane.showMessageDialog(null, "Venta Detalle no registrada.");
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //Codigo que permite insertar registros en al base de datos
        try {
            Connection cn = DriverManager.getConnection(Multibodega.Base_de_Datos, Multibodega.Usuario, Multibodega.Clave);
            PreparedStatement pst = cn.prepareStatement("insert into Venta_Detalle values(?,?,?,?,?,?,?)");

            pst.setString(1, txt_Orden_Venta.getText().trim());
            pst.setString(2, txt_Precio_Venta.getText().trim());
            pst.setString(3, txt_Cantidad_Venta.getText().trim());
            pst.setString(4, txt_Costo_Venta.getText().trim());
            pst.setString(5, txt_ID_Inventario.getText().trim());
            pst.setString(6, txt_ID_Productos.getText().trim());
            pst.setString(7, txt_ID_VentaE.getText().trim());

            pst.executeUpdate();

            txt_ID_VentaE.setText("");
            txt_Cantidad_Venta.setText("");
            txt_Costo_Venta.setText("");
            txt_ID_Inventario.setText("");
            txt_ID_Productos.setText("");
            txt_Orden_Venta.setText("");
            txt_Precio_Venta.setText("");

            lbl_estatus.setText("Registro exitoso.");
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_estatus;
    private javax.swing.JTextField txt_Cantidad_Venta;
    private javax.swing.JTextField txt_Costo_Venta;
    private javax.swing.JTextField txt_ID_Inventario;
    private javax.swing.JTextField txt_ID_Productos;
    private javax.swing.JTextField txt_ID_VentaE;
    private javax.swing.JTextField txt_Orden_Venta;
    private javax.swing.JTextField txt_Precio_Venta;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
