/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Multibodega;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Brayan Cifuentes
 */
public class Venta_Encabezado extends javax.swing.JInternalFrame {

    /**
     * Creates new form Venta_Encabezado
     */
    public Venta_Encabezado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_ID_VentaEn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_ID_Informe = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_ID_Cliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_Total_Venta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_Fecha_Venta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_Estatus_Venta = new javax.swing.JTextField();
        txt_buscar = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lbl_estatus = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(680, 445));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Venta Encabezado:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 22, -1, -1));

        jLabel2.setText("ID Venta Encabezado:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 60, -1, -1));
        getContentPane().add(txt_ID_VentaEn, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 60, 101, -1));

        jLabel6.setText("ID Informe");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));
        getContentPane().add(txt_ID_Informe, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 101, -1));

        jLabel7.setText("ID Cliente");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));
        getContentPane().add(txt_ID_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 101, -1));

        jLabel8.setText("Total Venta:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        getContentPane().add(txt_Total_Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 101, -1));

        jLabel9.setText("Fecha Venta:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));
        getContentPane().add(txt_Fecha_Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 101, -1));

        jLabel10.setText("Estatus Venta:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        getContentPane().add(txt_Estatus_Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 101, -1));
        getContentPane().add(txt_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 110, 106, -1));

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 150, -1, -1));

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 60, -1, -1));

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 60, -1, -1));

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 60, -1, -1));

        jLabel11.setText("Ingrese el ID Venta Encabezado:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 120, -1, -1));

        lbl_estatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(lbl_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 180, 27));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        //Codigo que permite consultar registros en la base de datos
        try {
            Connection cn = DriverManager.getConnection(Multibodega.Base_de_Datos, Multibodega.Usuario, Multibodega.Clave);
            PreparedStatement pst = cn.prepareStatement("select * from Venta_Encabezado where ID_Venta = ?");
            pst.setString(1, txt_buscar.getText().trim());

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_ID_VentaEn.setText(rs.getString("ID_Venta"));
                txt_Fecha_Venta.setText(rs.getString("Fecha_Venta"));
                txt_Estatus_Venta.setText(rs.getString("Estatus_Venta"));
                txt_Total_Venta.setText(rs.getString("Total_Venta"));
                txt_ID_Informe.setText(rs.getString("Id_Informe"));
                txt_ID_Cliente.setText(rs.getString("Id_Cliente"));

            } else {
                JOptionPane.showMessageDialog(null, "Venta Encabezado no registrada.");
            }

        } catch (Exception e) {
            System.out.println(e);

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //Codigo que permite insertar registros en al base de datos
        try {
            Connection cn = DriverManager.getConnection(Multibodega.Base_de_Datos, Multibodega.Usuario, Multibodega.Clave);
            PreparedStatement pst = cn.prepareStatement("insert into Venta_Encabezado values(?,?,?,?,?,?)");

            pst.setString(1, txt_ID_VentaEn.getText().trim());
            pst.setString(2, txt_Fecha_Venta.getText().trim());
            pst.setString(3, txt_Estatus_Venta.getText().trim());
            pst.setString(4, txt_Total_Venta.getText().trim());
            pst.setString(5, txt_ID_Informe.getText().trim());
            pst.setString(6, txt_ID_Cliente.getText().trim());

            pst.executeUpdate();

            txt_ID_VentaEn.setText("");
            txt_ID_Informe.setText("");
            txt_ID_Cliente.setText("");
            txt_Total_Venta.setText("");
            txt_Fecha_Venta.setText("");
            txt_Estatus_Venta.setText("");

            lbl_estatus.setText("Registro exitoso.");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Codigo que permite modificar registros en la base de datos
        try {
            String ID = txt_buscar.getText().trim();

            Connection cn = DriverManager.getConnection(Multibodega.Base_de_Datos, Multibodega.Usuario, Multibodega.Clave);
            PreparedStatement pst = cn.prepareStatement("update Venta_Encabezado set ID_Venta = ?, Fecha_Venta=?, Estatus_Venta=?, Total_Venta=?,Id_Informe=?, Id_Cliente=? where ID_Venta = " + ID);

            pst.setString(1, txt_ID_VentaEn.getText().trim());
            pst.setString(2, txt_Fecha_Venta.getText().trim());
            pst.setString(3, txt_Estatus_Venta.getText().trim());
            pst.setString(4, txt_Total_Venta.getText().trim());
            pst.setString(5, txt_ID_Informe.getText().trim());
            pst.setString(6, txt_ID_Cliente.getText().trim());

            pst.executeUpdate();

            txt_buscar.setText("");
            lbl_estatus.setText("Modificación exitosa.");

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Codigo que permite borrar registros en la base de datos
        try {
            Connection cn = DriverManager.getConnection(Multibodega.Base_de_Datos, Multibodega.Usuario, Multibodega.Clave);
            PreparedStatement pst = cn.prepareStatement("delete from Venta_Encabezado where ID_Venta = ?");

            pst.setString(1, txt_buscar.getText().trim());
            pst.executeUpdate();

            txt_ID_VentaEn.setText("");
            txt_Fecha_Venta.setText("");
            txt_Estatus_Venta.setText("");
            txt_Total_Venta.setText("");
            txt_ID_Informe.setText("");
            txt_ID_Cliente.setText("");

            lbl_estatus.setText("Registro eliminado.");

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_estatus;
    private javax.swing.JTextField txt_Estatus_Venta;
    private javax.swing.JTextField txt_Fecha_Venta;
    private javax.swing.JTextField txt_ID_Cliente;
    private javax.swing.JTextField txt_ID_Informe;
    private javax.swing.JTextField txt_ID_VentaEn;
    private javax.swing.JTextField txt_Total_Venta;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
